### ISSUE TITLE
How ionic.native is installed ?

### ISSUE THREAD

**Issue by kjakub** [driftyco/ionic1-deeplinks-demo#1]
How did you get ionic,native installed ? How do i install it to existing project ?

**Comment by pdsullivan** [comment]
Yes, i was wondering this same thing 👍

**Comment by kjakub** [comment]
I getaway form this weird thing to cordova deeplinking and works like charm..

**Comment by alexislg2** [comment]
@kjakub I don't understand what is your solution

**Comment by kjakub** [comment]
@alexislg2 i went for [https://github.com/nordnet/cordova-universal-links-plugin](https://github.com/nordnet/cordova-universal-links-plugin)
